version = 0.1
[default.deploy.parameters]
stack_name = "ChessAnalyzer"
resolve_s3 = true
s3_prefix = "ChessAnalyzer"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
